# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computation-msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='computation-msgs.proto',
  package='protoBuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63omputation-msgs.proto\x12\x08protoBuf\x1a\x19google/protobuf/any.proto\"D\n\x0e\x43omputeRequest\x12\x0f\n\x07\x61lgo_id\x18\x01 \x01(\x05\x12!\n\x03req\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"9\n\x0f\x43omputeResponse\x12&\n\x08response\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"@\n\x10\x43omputeResponses\x12,\n\tresponses\x18\x01 \x03(\x0b\x32\x19.protoBuf.ComputeResponse\"\x1a\n\x0bIntResponse\x12\x0b\n\x03val\x18\x01 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='protoBuf.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algo_id', full_name='protoBuf.ComputeRequest.algo_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='req', full_name='protoBuf.ComputeRequest.req', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=131,
)


_COMPUTERESPONSE = _descriptor.Descriptor(
  name='ComputeResponse',
  full_name='protoBuf.ComputeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='protoBuf.ComputeResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=190,
)


_COMPUTERESPONSES = _descriptor.Descriptor(
  name='ComputeResponses',
  full_name='protoBuf.ComputeResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='protoBuf.ComputeResponses.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=256,
)


_INTRESPONSE = _descriptor.Descriptor(
  name='IntResponse',
  full_name='protoBuf.IntResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='protoBuf.IntResponse.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=284,
)

_COMPUTEREQUEST.fields_by_name['req'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_COMPUTERESPONSE.fields_by_name['response'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_COMPUTERESPONSES.fields_by_name['responses'].message_type = _COMPUTERESPONSE
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeResponse'] = _COMPUTERESPONSE
DESCRIPTOR.message_types_by_name['ComputeResponses'] = _COMPUTERESPONSES
DESCRIPTOR.message_types_by_name['IntResponse'] = _INTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:protoBuf.ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

ComputeResponse = _reflection.GeneratedProtocolMessageType('ComputeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERESPONSE,
  '__module__' : 'computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:protoBuf.ComputeResponse)
  })
_sym_db.RegisterMessage(ComputeResponse)

ComputeResponses = _reflection.GeneratedProtocolMessageType('ComputeResponses', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERESPONSES,
  '__module__' : 'computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:protoBuf.ComputeResponses)
  })
_sym_db.RegisterMessage(ComputeResponses)

IntResponse = _reflection.GeneratedProtocolMessageType('IntResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTRESPONSE,
  '__module__' : 'computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:protoBuf.IntResponse)
  })
_sym_db.RegisterMessage(IntResponse)


# @@protoc_insertion_point(module_scope)
