// Code generated by protoc-gen-go. DO NOT EDIT.
// source: computation.proto

package protoBuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Patient_Gender int32

const (
	Patient_MALE   Patient_Gender = 0
	Patient_FEMALE Patient_Gender = 1
	Patient_OTHER  Patient_Gender = 2
)

var Patient_Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}

var Patient_Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x Patient_Gender) String() string {
	return proto.EnumName(Patient_Gender_name, int32(x))
}

func (Patient_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{5, 0}
}

// Message relayed by an algo to coordinator and site-connector that contains the query to be performed and algo id
type ComputeRequest struct {
	AlgoId               int32    `protobuf:"varint,1,opt,name=algo_id,json=algoId,proto3" json:"algo_id,omitempty"`
	Req                  *any.Any `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeRequest) Reset()         { *m = ComputeRequest{} }
func (m *ComputeRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeRequest) ProtoMessage()    {}
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{0}
}

func (m *ComputeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeRequest.Unmarshal(m, b)
}
func (m *ComputeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeRequest.Marshal(b, m, deterministic)
}
func (m *ComputeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeRequest.Merge(m, src)
}
func (m *ComputeRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeRequest.Size(m)
}
func (m *ComputeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeRequest proto.InternalMessageInfo

func (m *ComputeRequest) GetAlgoId() int32 {
	if m != nil {
		return m.AlgoId
	}
	return 0
}

func (m *ComputeRequest) GetReq() *any.Any {
	if m != nil {
		return m.Req
	}
	return nil
}

type ComputeResponse struct {
	Response             *any.Any `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeResponse) Reset()         { *m = ComputeResponse{} }
func (m *ComputeResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeResponse) ProtoMessage()    {}
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{1}
}

func (m *ComputeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeResponse.Unmarshal(m, b)
}
func (m *ComputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeResponse.Marshal(b, m, deterministic)
}
func (m *ComputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeResponse.Merge(m, src)
}
func (m *ComputeResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeResponse.Size(m)
}
func (m *ComputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeResponse proto.InternalMessageInfo

func (m *ComputeResponse) GetResponse() *any.Any {
	if m != nil {
		return m.Response
	}
	return nil
}

type ComputeResponses struct {
	Responses            []*ComputeResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ComputeResponses) Reset()         { *m = ComputeResponses{} }
func (m *ComputeResponses) String() string { return proto.CompactTextString(m) }
func (*ComputeResponses) ProtoMessage()    {}
func (*ComputeResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{2}
}

func (m *ComputeResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeResponses.Unmarshal(m, b)
}
func (m *ComputeResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeResponses.Marshal(b, m, deterministic)
}
func (m *ComputeResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeResponses.Merge(m, src)
}
func (m *ComputeResponses) XXX_Size() int {
	return xxx_messageInfo_ComputeResponses.Size(m)
}
func (m *ComputeResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeResponses.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeResponses proto.InternalMessageInfo

func (m *ComputeResponses) GetResponses() []*ComputeResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type IntResponse struct {
	Val                  int32    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntResponse) Reset()         { *m = IntResponse{} }
func (m *IntResponse) String() string { return proto.CompactTextString(m) }
func (*IntResponse) ProtoMessage()    {}
func (*IntResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{3}
}

func (m *IntResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntResponse.Unmarshal(m, b)
}
func (m *IntResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntResponse.Marshal(b, m, deterministic)
}
func (m *IntResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntResponse.Merge(m, src)
}
func (m *IntResponse) XXX_Size() int {
	return xxx_messageInfo_IntResponse.Size(m)
}
func (m *IntResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IntResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IntResponse proto.InternalMessageInfo

func (m *IntResponse) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

// Simple example query
type Query struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	StringValue          string   `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	NumericValue         int32    `protobuf:"varint,4,opt,name=numeric_value,json=numericValue,proto3" json:"numeric_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{4}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Query) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Query) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Query) GetNumericValue() int32 {
	if m != nil {
		return m.NumericValue
	}
	return 0
}

type Patient struct {
	FirstName            string         `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string         `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age                  int32          `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender               Patient_Gender `protobuf:"varint,5,opt,name=gender,proto3,enum=protoBuf.Patient_Gender" json:"gender,omitempty"`
	Weight               float32        `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Height               int32          `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Patient) Reset()         { *m = Patient{} }
func (m *Patient) String() string { return proto.CompactTextString(m) }
func (*Patient) ProtoMessage()    {}
func (*Patient) Descriptor() ([]byte, []int) {
	return fileDescriptor_61bd86b0865082ff, []int{5}
}

func (m *Patient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patient.Unmarshal(m, b)
}
func (m *Patient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patient.Marshal(b, m, deterministic)
}
func (m *Patient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patient.Merge(m, src)
}
func (m *Patient) XXX_Size() int {
	return xxx_messageInfo_Patient.Size(m)
}
func (m *Patient) XXX_DiscardUnknown() {
	xxx_messageInfo_Patient.DiscardUnknown(m)
}

var xxx_messageInfo_Patient proto.InternalMessageInfo

func (m *Patient) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Patient) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Patient) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Patient) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Patient) GetGender() Patient_Gender {
	if m != nil {
		return m.Gender
	}
	return Patient_MALE
}

func (m *Patient) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Patient) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("protoBuf.Patient_Gender", Patient_Gender_name, Patient_Gender_value)
	proto.RegisterType((*ComputeRequest)(nil), "protoBuf.ComputeRequest")
	proto.RegisterType((*ComputeResponse)(nil), "protoBuf.ComputeResponse")
	proto.RegisterType((*ComputeResponses)(nil), "protoBuf.ComputeResponses")
	proto.RegisterType((*IntResponse)(nil), "protoBuf.IntResponse")
	proto.RegisterType((*Query)(nil), "protoBuf.Query")
	proto.RegisterType((*Patient)(nil), "protoBuf.Patient")
}

func init() { proto.RegisterFile("computation.proto", fileDescriptor_61bd86b0865082ff) }

var fileDescriptor_61bd86b0865082ff = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xed, 0x92, 0x26, 0xaf, 0x63, 0x14, 0xab, 0x82, 0x6c, 0x08, 0x11, 0x82, 0x84, 0xc2,
	0x25, 0x9b, 0xca, 0x81, 0xf3, 0x98, 0x0a, 0x4c, 0xfc, 0x9c, 0x85, 0xb8, 0x56, 0xde, 0xfa, 0x9a,
	0x59, 0x4a, 0xec, 0xce, 0x71, 0x86, 0x7a, 0xe4, 0xdf, 0xe6, 0x84, 0x62, 0x3b, 0x99, 0x34, 0x89,
	0x53, 0xde, 0xf7, 0xc3, 0x9f, 0xbf, 0x67, 0x05, 0x1e, 0x5f, 0xa9, 0x7a, 0xdb, 0x1a, 0x6e, 0x84,
	0x92, 0xc5, 0x56, 0x2b, 0xa3, 0x68, 0x64, 0x3f, 0xef, 0xdb, 0xcd, 0xd1, 0x61, 0xa9, 0x54, 0x59,
	0xe1, 0xb1, 0x25, 0x2e, 0xdb, 0xcd, 0x31, 0x97, 0x3b, 0x67, 0xca, 0x2e, 0xe0, 0xe0, 0xcc, 0x9e,
	0x44, 0x86, 0x37, 0x2d, 0x36, 0x86, 0x3e, 0x85, 0x09, 0xaf, 0x4a, 0xb5, 0x12, 0xeb, 0x84, 0xa4,
	0x24, 0x0f, 0x58, 0xd8, 0xc1, 0xf3, 0x35, 0x7d, 0x0d, 0x63, 0x8d, 0x37, 0xc9, 0x28, 0x25, 0xf9,
	0x74, 0x31, 0x2f, 0x5c, 0x66, 0xd1, 0x67, 0x16, 0xa7, 0x72, 0xc7, 0x3a, 0x43, 0x76, 0x06, 0x8f,
	0x86, 0xc8, 0x66, 0xab, 0x64, 0x83, 0xf4, 0x04, 0x22, 0xed, 0x67, 0x1b, 0xfa, 0xbf, 0xf3, 0x83,
	0x2b, 0xfb, 0x0c, 0xb3, 0x7b, 0x21, 0x0d, 0x7d, 0x07, 0x71, 0xaf, 0x37, 0x09, 0x49, 0xc7, 0xf9,
	0x74, 0x71, 0x58, 0xf4, 0x4b, 0x16, 0xf7, 0xec, 0xec, 0xce, 0x9b, 0xbd, 0x80, 0xe9, 0xb9, 0x34,
	0x43, 0x9b, 0x19, 0x8c, 0x6f, 0x79, 0xe5, 0xb7, 0xeb, 0xc6, 0xec, 0x0f, 0x81, 0xe0, 0xa2, 0x45,
	0xbd, 0xa3, 0x47, 0x10, 0xa9, 0x2d, 0x6a, 0x6e, 0x94, 0xb6, 0x86, 0x98, 0x0d, 0x98, 0xce, 0x21,
	0xd8, 0x08, 0xac, 0xd6, 0xf6, 0x09, 0x62, 0xe6, 0x00, 0x7d, 0x09, 0xfb, 0x8d, 0xd1, 0x42, 0x96,
	0xab, 0x5b, 0x5e, 0xb5, 0x98, 0x8c, 0xad, 0x38, 0x75, 0xdc, 0xaf, 0x8e, 0xa2, 0xaf, 0xe0, 0xa1,
	0x6c, 0x6b, 0xd4, 0xe2, 0xca, 0x7b, 0xf6, 0xec, 0xd5, 0xfb, 0x9e, 0xb4, 0xa6, 0xec, 0x2f, 0x81,
	0xc9, 0x0f, 0x6e, 0x04, 0x4a, 0x43, 0x9f, 0x03, 0x6c, 0x84, 0x6e, 0xcc, 0x4a, 0xf2, 0x1a, 0x7d,
	0x8f, 0xd8, 0x32, 0xdf, 0x78, 0x8d, 0xf4, 0x19, 0xc4, 0x15, 0xef, 0x55, 0x57, 0x26, 0xea, 0x08,
	0x2b, 0xce, 0x21, 0xc0, 0x9a, 0x8b, 0xca, 0x17, 0x71, 0xa0, 0xdb, 0x99, 0x97, 0xfd, 0xc5, 0xdd,
	0x48, 0x4f, 0x20, 0x2c, 0x51, 0xae, 0x51, 0x27, 0x41, 0x4a, 0xf2, 0x83, 0x45, 0x72, 0xf7, 0x94,
	0xbe, 0x46, 0xf1, 0xd1, 0xea, 0xcc, 0xfb, 0xe8, 0x13, 0x08, 0x7f, 0xa3, 0x28, 0xaf, 0x4d, 0x12,
	0xa6, 0x24, 0x1f, 0x31, 0x8f, 0x3a, 0xfe, 0xda, 0xf1, 0x13, 0xf7, 0xc3, 0x38, 0x94, 0xbd, 0x81,
	0xd0, 0x25, 0xd0, 0x08, 0xf6, 0xbe, 0x9e, 0x7e, 0x59, 0xce, 0x1e, 0x50, 0x80, 0xf0, 0xc3, 0xd2,
	0xce, 0x84, 0xc6, 0x10, 0x7c, 0xff, 0xf9, 0x69, 0xc9, 0x66, 0xa3, 0xcb, 0xd0, 0xde, 0xfd, 0xf6,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x8c, 0xc1, 0xaa, 0xc7, 0x02, 0x00, 0x00,
}
