// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registration-msgs.proto

package protoBuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message sent by a site algo to a site connector indicating an algorithm it wants to register.
type SiteAlgoRegReq struct {
	AlgoId               int32    `protobuf:"varint,1,opt,name=algo_id,json=algoId,proto3" json:"algo_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProtoVersion         string   `protobuf:"bytes,3,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	AlgoIpPort           string   `protobuf:"bytes,4,opt,name=algo_ip_port,json=algoIpPort,proto3" json:"algo_ip_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiteAlgoRegReq) Reset()         { *m = SiteAlgoRegReq{} }
func (m *SiteAlgoRegReq) String() string { return proto.CompactTextString(m) }
func (*SiteAlgoRegReq) ProtoMessage()    {}
func (*SiteAlgoRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af0ccebd529e76fa, []int{0}
}

func (m *SiteAlgoRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteAlgoRegReq.Unmarshal(m, b)
}
func (m *SiteAlgoRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteAlgoRegReq.Marshal(b, m, deterministic)
}
func (m *SiteAlgoRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteAlgoRegReq.Merge(m, src)
}
func (m *SiteAlgoRegReq) XXX_Size() int {
	return xxx_messageInfo_SiteAlgoRegReq.Size(m)
}
func (m *SiteAlgoRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteAlgoRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_SiteAlgoRegReq proto.InternalMessageInfo

func (m *SiteAlgoRegReq) GetAlgoId() int32 {
	if m != nil {
		return m.AlgoId
	}
	return 0
}

func (m *SiteAlgoRegReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SiteAlgoRegReq) GetProtoVersion() string {
	if m != nil {
		return m.ProtoVersion
	}
	return ""
}

func (m *SiteAlgoRegReq) GetAlgoIpPort() string {
	if m != nil {
		return m.AlgoIpPort
	}
	return ""
}

// Message sent by a site connector to a coordinator with the registration request of a site algo.
type SiteRegReq struct {
	SiteId               int32           `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SiteIpPort           string          `protobuf:"bytes,2,opt,name=site_ip_port,json=siteIpPort,proto3" json:"site_ip_port,omitempty"`
	Req                  *SiteAlgoRegReq `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SiteRegReq) Reset()         { *m = SiteRegReq{} }
func (m *SiteRegReq) String() string { return proto.CompactTextString(m) }
func (*SiteRegReq) ProtoMessage()    {}
func (*SiteRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af0ccebd529e76fa, []int{1}
}

func (m *SiteRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteRegReq.Unmarshal(m, b)
}
func (m *SiteRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteRegReq.Marshal(b, m, deterministic)
}
func (m *SiteRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteRegReq.Merge(m, src)
}
func (m *SiteRegReq) XXX_Size() int {
	return xxx_messageInfo_SiteRegReq.Size(m)
}
func (m *SiteRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_SiteRegReq proto.InternalMessageInfo

func (m *SiteRegReq) GetSiteId() int32 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

func (m *SiteRegReq) GetSiteIpPort() string {
	if m != nil {
		return m.SiteIpPort
	}
	return ""
}

func (m *SiteRegReq) GetReq() *SiteAlgoRegReq {
	if m != nil {
		return m.Req
	}
	return nil
}

// Message sent by a coordinator to a site connector indicating whether the algorithm registration was successful.
type SiteAlgoRegRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiteAlgoRegRes) Reset()         { *m = SiteAlgoRegRes{} }
func (m *SiteAlgoRegRes) String() string { return proto.CompactTextString(m) }
func (*SiteAlgoRegRes) ProtoMessage()    {}
func (*SiteAlgoRegRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_af0ccebd529e76fa, []int{2}
}

func (m *SiteAlgoRegRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiteAlgoRegRes.Unmarshal(m, b)
}
func (m *SiteAlgoRegRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiteAlgoRegRes.Marshal(b, m, deterministic)
}
func (m *SiteAlgoRegRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiteAlgoRegRes.Merge(m, src)
}
func (m *SiteAlgoRegRes) XXX_Size() int {
	return xxx_messageInfo_SiteAlgoRegRes.Size(m)
}
func (m *SiteAlgoRegRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SiteAlgoRegRes.DiscardUnknown(m)
}

var xxx_messageInfo_SiteAlgoRegRes proto.InternalMessageInfo

func (m *SiteAlgoRegRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SiteAlgoRegRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Message sent by a cloud algorithm to a coordinator indicating this algorithm should be registered.
type CloudAlgoRegReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProtoVersion         string   `protobuf:"bytes,3,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	AlgoIpPort           string   `protobuf:"bytes,4,opt,name=algo_ip_port,json=algoIpPort,proto3" json:"algo_ip_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudAlgoRegReq) Reset()         { *m = CloudAlgoRegReq{} }
func (m *CloudAlgoRegReq) String() string { return proto.CompactTextString(m) }
func (*CloudAlgoRegReq) ProtoMessage()    {}
func (*CloudAlgoRegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af0ccebd529e76fa, []int{3}
}

func (m *CloudAlgoRegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudAlgoRegReq.Unmarshal(m, b)
}
func (m *CloudAlgoRegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudAlgoRegReq.Marshal(b, m, deterministic)
}
func (m *CloudAlgoRegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudAlgoRegReq.Merge(m, src)
}
func (m *CloudAlgoRegReq) XXX_Size() int {
	return xxx_messageInfo_CloudAlgoRegReq.Size(m)
}
func (m *CloudAlgoRegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudAlgoRegReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloudAlgoRegReq proto.InternalMessageInfo

func (m *CloudAlgoRegReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CloudAlgoRegReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CloudAlgoRegReq) GetProtoVersion() string {
	if m != nil {
		return m.ProtoVersion
	}
	return ""
}

func (m *CloudAlgoRegReq) GetAlgoIpPort() string {
	if m != nil {
		return m.AlgoIpPort
	}
	return ""
}

// Message sent by a coordinator to a cloud algorithm indicating whether the algorithm registration was successful.
type CloudAlgoRegRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudAlgoRegRes) Reset()         { *m = CloudAlgoRegRes{} }
func (m *CloudAlgoRegRes) String() string { return proto.CompactTextString(m) }
func (*CloudAlgoRegRes) ProtoMessage()    {}
func (*CloudAlgoRegRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_af0ccebd529e76fa, []int{4}
}

func (m *CloudAlgoRegRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudAlgoRegRes.Unmarshal(m, b)
}
func (m *CloudAlgoRegRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudAlgoRegRes.Marshal(b, m, deterministic)
}
func (m *CloudAlgoRegRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudAlgoRegRes.Merge(m, src)
}
func (m *CloudAlgoRegRes) XXX_Size() int {
	return xxx_messageInfo_CloudAlgoRegRes.Size(m)
}
func (m *CloudAlgoRegRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudAlgoRegRes.DiscardUnknown(m)
}

var xxx_messageInfo_CloudAlgoRegRes proto.InternalMessageInfo

func (m *CloudAlgoRegRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CloudAlgoRegRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SiteAlgoRegReq)(nil), "protoBuf.SiteAlgoRegReq")
	proto.RegisterType((*SiteRegReq)(nil), "protoBuf.SiteRegReq")
	proto.RegisterType((*SiteAlgoRegRes)(nil), "protoBuf.SiteAlgoRegRes")
	proto.RegisterType((*CloudAlgoRegReq)(nil), "protoBuf.CloudAlgoRegReq")
	proto.RegisterType((*CloudAlgoRegRes)(nil), "protoBuf.CloudAlgoRegRes")
}

func init() { proto.RegisterFile("registration-msgs.proto", fileDescriptor_af0ccebd529e76fa) }

var fileDescriptor_af0ccebd529e76fa = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x04, 0xda, 0x72, 0x0d, 0x05, 0x79, 0xa9, 0xc7, 0x28, 0x2c, 0x15, 0x12, 0x19,
	0x60, 0x85, 0x01, 0x98, 0xd8, 0x90, 0x91, 0x58, 0xa3, 0x92, 0x18, 0xcb, 0x52, 0x8a, 0x5d, 0x9f,
	0xc3, 0x8f, 0x60, 0xe4, 0x17, 0x23, 0x5f, 0x5a, 0x08, 0xd9, 0x58, 0x98, 0xec, 0xbb, 0x7b, 0x7a,
	0xef, 0xbb, 0x83, 0xa5, 0x57, 0xda, 0x60, 0xf0, 0xeb, 0x60, 0xec, 0xdb, 0xc5, 0x06, 0x35, 0x96,
	0xce, 0xdb, 0x60, 0xf9, 0x8c, 0x9e, 0xbb, 0xee, 0xb5, 0xf8, 0x64, 0xb0, 0x78, 0x32, 0x41, 0xdd,
	0xb6, 0xda, 0x4a, 0xa5, 0xa5, 0xda, 0xf2, 0x25, 0x4c, 0xd7, 0xad, 0xb6, 0x95, 0x69, 0x04, 0xcb,
	0xd9, 0xea, 0x50, 0x4e, 0x62, 0xf9, 0xd0, 0xf0, 0x1c, 0xe6, 0x8d, 0xc2, 0xda, 0x1b, 0x17, 0xfd,
	0x44, 0x92, 0xb3, 0xd5, 0x91, 0x1c, 0xb6, 0xf8, 0x19, 0x1c, 0x93, 0x73, 0xf5, 0xae, 0x3c, 0x46,
	0x4d, 0x4a, 0x9a, 0x8c, 0x9a, 0xcf, 0x7d, 0x8f, 0xe7, 0x90, 0xf5, 0xfe, 0xae, 0x72, 0xd6, 0x07,
	0x71, 0x40, 0x1a, 0xa0, 0x10, 0xf7, 0x68, 0x7d, 0x28, 0x10, 0x20, 0x32, 0xfd, 0xf0, 0xa0, 0x09,
	0x6a, 0xc0, 0x13, 0x4b, 0xe2, 0xc9, 0xfa, 0xc1, 0xce, 0xa8, 0x07, 0x02, 0x9a, 0x92, 0x11, 0x3f,
	0x87, 0xd4, 0xab, 0x2d, 0x51, 0xcc, 0x2f, 0x45, 0xb9, 0xdf, 0xba, 0xfc, 0xbd, 0xb1, 0x8c, 0xa2,
	0xe2, 0x7a, 0x74, 0x08, 0xe4, 0x02, 0xa6, 0xd8, 0xd5, 0xb5, 0x42, 0xa4, 0xe0, 0x99, 0xdc, 0x97,
	0xfc, 0x14, 0xd2, 0x0d, 0xea, 0x5d, 0x60, 0xfc, 0x16, 0x1f, 0x0c, 0x4e, 0xee, 0x5b, 0xdb, 0x35,
	0x83, 0x43, 0x2e, 0x20, 0xf9, 0x66, 0x4e, 0xcc, 0x3f, 0xde, 0xef, 0x66, 0xcc, 0xf2, 0xa7, 0x5d,
	0x5e, 0x26, 0x14, 0x77, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x3f, 0x38, 0xbd, 0x3f, 0x02,
	0x00, 0x00,
}
