# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import computation_msgs_pb2 as computation__msgs__pb2


class SiteAlgoStub(object):
  """To compile the protobuf to Go run the following inside the protoBuf folder:
  protoc -I=. --go_out=plugins=grpc:.  site-algos.proto

  To compile the protobuf to Python run the following inside the protoBuf folder:
  python -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. site-algos.proto

  RPC service at a site algo that performs the necessary computation.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Compute = channel.unary_unary(
        '/protoBuf.SiteAlgo/Compute',
        request_serializer=computation__msgs__pb2.ComputeRequest.SerializeToString,
        response_deserializer=computation__msgs__pb2.ComputeResponse.FromString,
        )


class SiteAlgoServicer(object):
  """To compile the protobuf to Go run the following inside the protoBuf folder:
  protoc -I=. --go_out=plugins=grpc:.  site-algos.proto

  To compile the protobuf to Python run the following inside the protoBuf folder:
  python -m grpc_tools.protoc -I=. --python_out=. --grpc_python_out=. site-algos.proto

  RPC service at a site algo that performs the necessary computation.
  """

  def Compute(self, request, context):
    """Performs the appropriate computation at the host algo and returns the result.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SiteAlgoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Compute': grpc.unary_unary_rpc_method_handler(
          servicer.Compute,
          request_deserializer=computation__msgs__pb2.ComputeRequest.FromString,
          response_serializer=computation__msgs__pb2.ComputeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protoBuf.SiteAlgo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
