### Algo Code ###
COUNT_ALGO = "count_fn"
PRIVATE_COUNT_ALGO = "count_fn_dp"
SUM_ALGO = "sum_fn"
VARIANCE_ALGO = "var_fn"
FEDERATED_LEARNING_ALGO = "fl_fn"

### Leap Types ###
UDF = 1
LAPLACE_UDF = 2
EXPONENTIAL_UDF = 3
PREDEFINED = 4
PRIVATE_PREDEFINED = 5
FEDERATED_LEARNING = 6