# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/availability-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/availability-msgs.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dproto/availability-msgs.proto\x12\x05proto\"#\n\x10SiteAvailableReq\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\"-\n\x10SiteAvailableRes\x12\x19\n\x04site\x18\x01 \x01(\x0b\x32\x0b.proto.Site\"\x13\n\x11SitesAvailableReq\"?\n\x11SitesAvailableRes\x12*\n\tresponses\x18\x01 \x03(\x0b\x32\x17.proto.SiteAvailableRes\"*\n\x04Site\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\x12\x11\n\tavailable\x18\x02 \x01(\x08\x42\tZ\x07.;protob\x06proto3'
)




_SITEAVAILABLEREQ = _descriptor.Descriptor(
  name='SiteAvailableReq',
  full_name='proto.SiteAvailableReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='proto.SiteAvailableReq.site_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=75,
)


_SITEAVAILABLERES = _descriptor.Descriptor(
  name='SiteAvailableRes',
  full_name='proto.SiteAvailableRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='site', full_name='proto.SiteAvailableRes.site', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=122,
)


_SITESAVAILABLEREQ = _descriptor.Descriptor(
  name='SitesAvailableReq',
  full_name='proto.SitesAvailableReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=143,
)


_SITESAVAILABLERES = _descriptor.Descriptor(
  name='SitesAvailableRes',
  full_name='proto.SitesAvailableRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='proto.SitesAvailableRes.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=208,
)


_SITE = _descriptor.Descriptor(
  name='Site',
  full_name='proto.Site',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='proto.Site.site_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available', full_name='proto.Site.available', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=252,
)

_SITEAVAILABLERES.fields_by_name['site'].message_type = _SITE
_SITESAVAILABLERES.fields_by_name['responses'].message_type = _SITEAVAILABLERES
DESCRIPTOR.message_types_by_name['SiteAvailableReq'] = _SITEAVAILABLEREQ
DESCRIPTOR.message_types_by_name['SiteAvailableRes'] = _SITEAVAILABLERES
DESCRIPTOR.message_types_by_name['SitesAvailableReq'] = _SITESAVAILABLEREQ
DESCRIPTOR.message_types_by_name['SitesAvailableRes'] = _SITESAVAILABLERES
DESCRIPTOR.message_types_by_name['Site'] = _SITE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SiteAvailableReq = _reflection.GeneratedProtocolMessageType('SiteAvailableReq', (_message.Message,), {
  'DESCRIPTOR' : _SITEAVAILABLEREQ,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteAvailableReq)
  })
_sym_db.RegisterMessage(SiteAvailableReq)

SiteAvailableRes = _reflection.GeneratedProtocolMessageType('SiteAvailableRes', (_message.Message,), {
  'DESCRIPTOR' : _SITEAVAILABLERES,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteAvailableRes)
  })
_sym_db.RegisterMessage(SiteAvailableRes)

SitesAvailableReq = _reflection.GeneratedProtocolMessageType('SitesAvailableReq', (_message.Message,), {
  'DESCRIPTOR' : _SITESAVAILABLEREQ,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SitesAvailableReq)
  })
_sym_db.RegisterMessage(SitesAvailableReq)

SitesAvailableRes = _reflection.GeneratedProtocolMessageType('SitesAvailableRes', (_message.Message,), {
  'DESCRIPTOR' : _SITESAVAILABLERES,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SitesAvailableRes)
  })
_sym_db.RegisterMessage(SitesAvailableRes)

Site = _reflection.GeneratedProtocolMessageType('Site', (_message.Message,), {
  'DESCRIPTOR' : _SITE,
  '__module__' : 'proto.availability_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.Site)
  })
_sym_db.RegisterMessage(Site)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
