// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/computation-msgs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Leap types
type LeapTypes int32

const (
	LeapTypes_UDF                LeapTypes = 0
	LeapTypes_LAPLACE_UDF        LeapTypes = 1
	LeapTypes_EXPONENTIAL_UDF    LeapTypes = 2
	LeapTypes_PREDEFINED         LeapTypes = 3
	LeapTypes_PRIVATE_PREDEFINED LeapTypes = 4
	LeapTypes_FEDERATED_LEARNING LeapTypes = 5
)

// Enum value maps for LeapTypes.
var (
	LeapTypes_name = map[int32]string{
		0: "UDF",
		1: "LAPLACE_UDF",
		2: "EXPONENTIAL_UDF",
		3: "PREDEFINED",
		4: "PRIVATE_PREDEFINED",
		5: "FEDERATED_LEARNING",
	}
	LeapTypes_value = map[string]int32{
		"UDF":                0,
		"LAPLACE_UDF":        1,
		"EXPONENTIAL_UDF":    2,
		"PREDEFINED":         3,
		"PRIVATE_PREDEFINED": 4,
		"FEDERATED_LEARNING": 5,
	}
)

func (x LeapTypes) Enum() *LeapTypes {
	p := new(LeapTypes)
	*p = x
	return p
}

func (x LeapTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeapTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_computation_msgs_proto_enumTypes[0].Descriptor()
}

func (LeapTypes) Type() protoreflect.EnumType {
	return &file_proto_computation_msgs_proto_enumTypes[0]
}

func (x LeapTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeapTypes.Descriptor instead.
func (LeapTypes) EnumDescriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{0}
}

// Algo codes
type AlgoCodes int32

const (
	AlgoCodes_COUNT_ALGO               AlgoCodes = 0
	AlgoCodes_PRIVATE_SITE_COUNT_ALGO  AlgoCodes = 1
	AlgoCodes_PRIVATE_CLOUD_COUNT_ALGO AlgoCodes = 2
	AlgoCodes_SUM_ALGO                 AlgoCodes = 3
	AlgoCodes_VARIANCE_ALGO            AlgoCodes = 4
	AlgoCodes_FEDERATED_LEARNING_ALGO  AlgoCodes = 5
	AlgoCodes_QUANTILE_ALGO            AlgoCodes = 6
	AlgoCodes_COUNT_ALGO_RC            AlgoCodes = 7
	AlgoCodes_COUNT_ALGO_RC_QUERY      AlgoCodes = 8
	AlgoCodes_MAX_ALGO_RC              AlgoCodes = 9
	AlgoCodes_MEAN_ALGO                AlgoCodes = 10
	AlgoCodes_LOG_REG                  AlgoCodes = 11
)

// Enum value maps for AlgoCodes.
var (
	AlgoCodes_name = map[int32]string{
		0:  "COUNT_ALGO",
		1:  "PRIVATE_SITE_COUNT_ALGO",
		2:  "PRIVATE_CLOUD_COUNT_ALGO",
		3:  "SUM_ALGO",
		4:  "VARIANCE_ALGO",
		5:  "FEDERATED_LEARNING_ALGO",
		6:  "QUANTILE_ALGO",
		7:  "COUNT_ALGO_RC",
		8:  "COUNT_ALGO_RC_QUERY",
		9:  "MAX_ALGO_RC",
		10: "MEAN_ALGO",
		11: "LOG_REG",
	}
	AlgoCodes_value = map[string]int32{
		"COUNT_ALGO":               0,
		"PRIVATE_SITE_COUNT_ALGO":  1,
		"PRIVATE_CLOUD_COUNT_ALGO": 2,
		"SUM_ALGO":                 3,
		"VARIANCE_ALGO":            4,
		"FEDERATED_LEARNING_ALGO":  5,
		"QUANTILE_ALGO":            6,
		"COUNT_ALGO_RC":            7,
		"COUNT_ALGO_RC_QUERY":      8,
		"MAX_ALGO_RC":              9,
		"MEAN_ALGO":                10,
		"LOG_REG":                  11,
	}
)

func (x AlgoCodes) Enum() *AlgoCodes {
	p := new(AlgoCodes)
	*p = x
	return p
}

func (x AlgoCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlgoCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_computation_msgs_proto_enumTypes[1].Descriptor()
}

func (AlgoCodes) Type() protoreflect.EnumType {
	return &file_proto_computation_msgs_proto_enumTypes[1]
}

func (x AlgoCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlgoCodes.Descriptor instead.
func (AlgoCodes) EnumDescriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{1}
}

// TODO: Better way to link users to a request
// A generic JSON encoded request
type ComputeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Req      string    `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	LeapType LeapTypes `protobuf:"varint,3,opt,name=leap_type,json=leapType,proto3,enum=proto.LeapTypes" json:"leap_type,omitempty"`
	AlgoCode AlgoCodes `protobuf:"varint,4,opt,name=algo_code,json=algoCode,proto3,enum=proto.AlgoCodes" json:"algo_code,omitempty"`
	Eps      float32   `protobuf:"fixed32,5,opt,name=eps,proto3" json:"eps,omitempty"`
	Delt     float32   `protobuf:"fixed32,6,opt,name=delt,proto3" json:"delt,omitempty"`
	Sites    []int64   `protobuf:"varint,7,rep,packed,name=sites,proto3" json:"sites,omitempty"`
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ComputeRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

func (x *ComputeRequest) GetLeapType() LeapTypes {
	if x != nil {
		return x.LeapType
	}
	return LeapTypes_UDF
}

func (x *ComputeRequest) GetAlgoCode() AlgoCodes {
	if x != nil {
		return x.AlgoCode
	}
	return AlgoCodes_COUNT_ALGO
}

func (x *ComputeRequest) GetEps() float32 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *ComputeRequest) GetDelt() float32 {
	if x != nil {
		return x.Delt
	}
	return 0
}

func (x *ComputeRequest) GetSites() []int64 {
	if x != nil {
		return x.Sites
	}
	return nil
}

// A generic JSON encoded response
type ComputeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response         string  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Eps              float32 `protobuf:"fixed32,2,opt,name=eps,proto3" json:"eps,omitempty"`
	Delt             float32 `protobuf:"fixed32,3,opt,name=delt,proto3" json:"delt,omitempty"`
	Private          bool    `protobuf:"varint,4,opt,name=private,proto3" json:"private,omitempty"`
	UnavailableSites []int64 `protobuf:"varint,5,rep,packed,name=unavailable_sites,json=unavailableSites,proto3" json:"unavailable_sites,omitempty"`
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ComputeResponse) GetEps() float32 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *ComputeResponse) GetDelt() float32 {
	if x != nil {
		return x.Delt
	}
	return 0
}

func (x *ComputeResponse) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *ComputeResponse) GetUnavailableSites() []int64 {
	if x != nil {
		return x.UnavailableSites
	}
	return nil
}

type MapRequestChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *MapRequestChunk) Reset() {
	*x = MapRequestChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapRequestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRequestChunk) ProtoMessage() {}

func (x *MapRequestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRequestChunk.ProtoReflect.Descriptor instead.
func (*MapRequestChunk) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *MapRequestChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// A request for a map computation
type MapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Req          string    `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	LeapType     LeapTypes `protobuf:"varint,3,opt,name=leap_type,json=leapType,proto3,enum=proto.LeapTypes" json:"leap_type,omitempty"`
	AlgoCode     AlgoCodes `protobuf:"varint,4,opt,name=algo_code,json=algoCode,proto3,enum=proto.AlgoCodes" json:"algo_code,omitempty"`
	Sites        []int64   `protobuf:"varint,7,rep,packed,name=sites,proto3" json:"sites,omitempty"`
	ModelWeights []byte    `protobuf:"bytes,8,opt,name=model_weights,json=modelWeights,proto3" json:"model_weights,omitempty"`
}

func (x *MapRequest) Reset() {
	*x = MapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRequest) ProtoMessage() {}

func (x *MapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRequest.ProtoReflect.Descriptor instead.
func (*MapRequest) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *MapRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapRequest) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

func (x *MapRequest) GetLeapType() LeapTypes {
	if x != nil {
		return x.LeapType
	}
	return LeapTypes_UDF
}

func (x *MapRequest) GetAlgoCode() AlgoCodes {
	if x != nil {
		return x.AlgoCode
	}
	return AlgoCodes_COUNT_ALGO
}

func (x *MapRequest) GetSites() []int64 {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *MapRequest) GetModelWeights() []byte {
	if x != nil {
		return x.ModelWeights
	}
	return nil
}

// Chunked compute response so we can transmit large files
type MapResponseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *MapResponseChunk) Reset() {
	*x = MapResponseChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponseChunk) ProtoMessage() {}

func (x *MapResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponseChunk.ProtoReflect.Descriptor instead.
func (*MapResponseChunk) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{4}
}

func (x *MapResponseChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// A response from a map computation
type MapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Grad     []byte `protobuf:"bytes,2,opt,name=grad,proto3" json:"grad,omitempty"`
}

func (x *MapResponse) Reset() {
	*x = MapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponse) ProtoMessage() {}

func (x *MapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponse.ProtoReflect.Descriptor instead.
func (*MapResponse) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{5}
}

func (x *MapResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *MapResponse) GetGrad() []byte {
	if x != nil {
		return x.Grad
	}
	return nil
}

// Chunked compute response so we can transmit large files
type MapResponsesChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *MapResponsesChunk) Reset() {
	*x = MapResponsesChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapResponsesChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponsesChunk) ProtoMessage() {}

func (x *MapResponsesChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponsesChunk.ProtoReflect.Descriptor instead.
func (*MapResponsesChunk) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{6}
}

func (x *MapResponsesChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// The map responses returned by the algorithms in different sites.
type MapResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses        []*MapResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	UnavailableSites []int64        `protobuf:"varint,2,rep,packed,name=unavailable_sites,json=unavailableSites,proto3" json:"unavailable_sites,omitempty"`
}

func (x *MapResponses) Reset() {
	*x = MapResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computation_msgs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapResponses) ProtoMessage() {}

func (x *MapResponses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computation_msgs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapResponses.ProtoReflect.Descriptor instead.
func (*MapResponses) Descriptor() ([]byte, []int) {
	return file_proto_computation_msgs_proto_rawDescGZIP(), []int{7}
}

func (x *MapResponses) GetResponses() []*MapResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *MapResponses) GetUnavailableSites() []int64 {
	if x != nil {
		return x.UnavailableSites
	}
	return nil
}

var File_proto_computation_msgs_proto protoreflect.FileDescriptor

var file_proto_computation_msgs_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x65,
	0x61, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x61, 0x6c, 0x67,
	0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x08,
	0x61, 0x6c, 0x67, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x65, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x64, 0x65, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x69, 0x74, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x65, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x64, 0x65, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x10, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x69, 0x74, 0x65,
	0x73, 0x22, 0x27, 0x0a, 0x0f, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0xc7, 0x01, 0x0a, 0x0a, 0x4d,
	0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x09, 0x6c,
	0x65, 0x61, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x52, 0x08, 0x6c, 0x65, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x61, 0x6c,
	0x67, 0x6f, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x08, 0x61, 0x6c, 0x67, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x74,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x73, 0x69, 0x74, 0x65, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x22, 0x28, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x3d,
	0x0a, 0x0b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x72, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x67, 0x72, 0x61, 0x64, 0x22, 0x29, 0x0a,
	0x11, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x6d, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x75, 0x6e,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x10, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x69, 0x74, 0x65, 0x73, 0x2a, 0x7a, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x46, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x4c, 0x41, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x5f, 0x55, 0x44, 0x46, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x5f, 0x55, 0x44,
	0x46, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x45, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x50,
	0x52, 0x45, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x46,
	0x45, 0x44, 0x45, 0x52, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x4c, 0x45, 0x41, 0x52, 0x4e, 0x49, 0x4e,
	0x47, 0x10, 0x05, 0x2a, 0x80, 0x02, 0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10,
	0x00, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x49, 0x54,
	0x45, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x01, 0x12, 0x1c,
	0x0a, 0x18, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x55, 0x44, 0x5f,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x55, 0x4d, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x56, 0x41,
	0x52, 0x49, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x04, 0x12, 0x1b, 0x0a,
	0x17, 0x46, 0x45, 0x44, 0x45, 0x52, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x4c, 0x45, 0x41, 0x52, 0x4e,
	0x49, 0x4e, 0x47, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x55,
	0x41, 0x4e, 0x54, 0x49, 0x4c, 0x45, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x06, 0x12, 0x11, 0x0a,
	0x0d, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x52, 0x43, 0x10, 0x07,
	0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x52,
	0x43, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x58,
	0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x5f, 0x52, 0x43, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x45,
	0x41, 0x4e, 0x5f, 0x41, 0x4c, 0x47, 0x4f, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x4f, 0x47,
	0x5f, 0x52, 0x45, 0x47, 0x10, 0x0b, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_computation_msgs_proto_rawDescOnce sync.Once
	file_proto_computation_msgs_proto_rawDescData = file_proto_computation_msgs_proto_rawDesc
)

func file_proto_computation_msgs_proto_rawDescGZIP() []byte {
	file_proto_computation_msgs_proto_rawDescOnce.Do(func() {
		file_proto_computation_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_computation_msgs_proto_rawDescData)
	})
	return file_proto_computation_msgs_proto_rawDescData
}

var file_proto_computation_msgs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_computation_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_computation_msgs_proto_goTypes = []interface{}{
	(LeapTypes)(0),            // 0: proto.LeapTypes
	(AlgoCodes)(0),            // 1: proto.AlgoCodes
	(*ComputeRequest)(nil),    // 2: proto.ComputeRequest
	(*ComputeResponse)(nil),   // 3: proto.ComputeResponse
	(*MapRequestChunk)(nil),   // 4: proto.MapRequestChunk
	(*MapRequest)(nil),        // 5: proto.MapRequest
	(*MapResponseChunk)(nil),  // 6: proto.MapResponseChunk
	(*MapResponse)(nil),       // 7: proto.MapResponse
	(*MapResponsesChunk)(nil), // 8: proto.MapResponsesChunk
	(*MapResponses)(nil),      // 9: proto.MapResponses
}
var file_proto_computation_msgs_proto_depIdxs = []int32{
	0, // 0: proto.ComputeRequest.leap_type:type_name -> proto.LeapTypes
	1, // 1: proto.ComputeRequest.algo_code:type_name -> proto.AlgoCodes
	0, // 2: proto.MapRequest.leap_type:type_name -> proto.LeapTypes
	1, // 3: proto.MapRequest.algo_code:type_name -> proto.AlgoCodes
	7, // 4: proto.MapResponses.responses:type_name -> proto.MapResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_computation_msgs_proto_init() }
func file_proto_computation_msgs_proto_init() {
	if File_proto_computation_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_computation_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComputeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapRequestChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapResponseChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapResponsesChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computation_msgs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_computation_msgs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_computation_msgs_proto_goTypes,
		DependencyIndexes: file_proto_computation_msgs_proto_depIdxs,
		EnumInfos:         file_proto_computation_msgs_proto_enumTypes,
		MessageInfos:      file_proto_computation_msgs_proto_msgTypes,
	}.Build()
	File_proto_computation_msgs_proto = out.File
	file_proto_computation_msgs_proto_rawDesc = nil
	file_proto_computation_msgs_proto_goTypes = nil
	file_proto_computation_msgs_proto_depIdxs = nil
}
