# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/computation-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/computation-msgs.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cproto/computation-msgs.proto\x12\x05proto\"\x9d\x01\n\x0e\x43omputeRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03req\x18\x02 \x01(\t\x12#\n\tleap_type\x18\x03 \x01(\x0e\x32\x10.proto.LeapTypes\x12#\n\talgo_code\x18\x04 \x01(\x0e\x32\x10.proto.AlgoCodes\x12\x0b\n\x03\x65ps\x18\x05 \x01(\x02\x12\x0c\n\x04\x64\x65lt\x18\x06 \x01(\x02\x12\r\n\x05sites\x18\x07 \x03(\x03\"j\n\x0f\x43omputeResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0b\n\x03\x65ps\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x65lt\x18\x03 \x01(\x02\x12\x0f\n\x07private\x18\x04 \x01(\x08\x12\x19\n\x11unavailable_sites\x18\x05 \x03(\x03\" \n\x0fMapRequestChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"~\n\nMapRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03req\x18\x02 \x01(\t\x12#\n\tleap_type\x18\x03 \x01(\x0e\x32\x10.proto.LeapTypes\x12#\n\talgo_code\x18\x04 \x01(\x0e\x32\x10.proto.AlgoCodes\x12\r\n\x05sites\x18\x07 \x03(\x03\"!\n\x10MapResponseChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\x1f\n\x0bMapResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\"\n\x11MapResponsesChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"P\n\x0cMapResponses\x12%\n\tresponses\x18\x01 \x03(\x0b\x32\x12.proto.MapResponse\x12\x19\n\x11unavailable_sites\x18\x02 \x03(\x03*z\n\tLeapTypes\x12\x07\n\x03UDF\x10\x00\x12\x0f\n\x0bLAPLACE_UDF\x10\x01\x12\x13\n\x0f\x45XPONENTIAL_UDF\x10\x02\x12\x0e\n\nPREDEFINED\x10\x03\x12\x16\n\x12PRIVATE_PREDEFINED\x10\x04\x12\x16\n\x12\x46\x45\x44\x45RATED_LEARNING\x10\x05*\x80\x02\n\tAlgoCodes\x12\x0e\n\nCOUNT_ALGO\x10\x00\x12\x1b\n\x17PRIVATE_SITE_COUNT_ALGO\x10\x01\x12\x1c\n\x18PRIVATE_CLOUD_COUNT_ALGO\x10\x02\x12\x0c\n\x08SUM_ALGO\x10\x03\x12\x11\n\rVARIANCE_ALGO\x10\x04\x12\x1b\n\x17\x46\x45\x44\x45RATED_LEARNING_ALGO\x10\x05\x12\x11\n\rQUANTILE_ALGO\x10\x06\x12\x11\n\rCOUNT_ALGO_RC\x10\x07\x12\x17\n\x13\x43OUNT_ALGO_RC_QUERY\x10\x08\x12\x0f\n\x0bMAX_ALGO_RC\x10\t\x12\r\n\tMEAN_ALGO\x10\n\x12\x0b\n\x07LOG_REG\x10\x0b\x42\tZ\x07.;protob\x06proto3'
)

_LEAPTYPES = _descriptor.EnumDescriptor(
  name='LeapTypes',
  full_name='proto.LeapTypes',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UDF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAPLACE_UDF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXPONENTIAL_UDF', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PREDEFINED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE_PREDEFINED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEDERATED_LEARNING', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=655,
  serialized_end=777,
)
_sym_db.RegisterEnumDescriptor(_LEAPTYPES)

LeapTypes = enum_type_wrapper.EnumTypeWrapper(_LEAPTYPES)
_ALGOCODES = _descriptor.EnumDescriptor(
  name='AlgoCodes',
  full_name='proto.AlgoCodes',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COUNT_ALGO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE_SITE_COUNT_ALGO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE_CLOUD_COUNT_ALGO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUM_ALGO', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VARIANCE_ALGO', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FEDERATED_LEARNING_ALGO', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUANTILE_ALGO', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_ALGO_RC', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COUNT_ALGO_RC_QUERY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAX_ALGO_RC', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEAN_ALGO', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOG_REG', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=780,
  serialized_end=1036,
)
_sym_db.RegisterEnumDescriptor(_ALGOCODES)

AlgoCodes = enum_type_wrapper.EnumTypeWrapper(_ALGOCODES)
UDF = 0
LAPLACE_UDF = 1
EXPONENTIAL_UDF = 2
PREDEFINED = 3
PRIVATE_PREDEFINED = 4
FEDERATED_LEARNING = 5
COUNT_ALGO = 0
PRIVATE_SITE_COUNT_ALGO = 1
PRIVATE_CLOUD_COUNT_ALGO = 2
SUM_ALGO = 3
VARIANCE_ALGO = 4
FEDERATED_LEARNING_ALGO = 5
QUANTILE_ALGO = 6
COUNT_ALGO_RC = 7
COUNT_ALGO_RC_QUERY = 8
MAX_ALGO_RC = 9
MEAN_ALGO = 10
LOG_REG = 11



_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='proto.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.ComputeRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req', full_name='proto.ComputeRequest.req', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leap_type', full_name='proto.ComputeRequest.leap_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algo_code', full_name='proto.ComputeRequest.algo_code', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eps', full_name='proto.ComputeRequest.eps', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delt', full_name='proto.ComputeRequest.delt', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sites', full_name='proto.ComputeRequest.sites', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=197,
)


_COMPUTERESPONSE = _descriptor.Descriptor(
  name='ComputeResponse',
  full_name='proto.ComputeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.ComputeResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eps', full_name='proto.ComputeResponse.eps', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delt', full_name='proto.ComputeResponse.delt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private', full_name='proto.ComputeResponse.private', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unavailable_sites', full_name='proto.ComputeResponse.unavailable_sites', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=305,
)


_MAPREQUESTCHUNK = _descriptor.Descriptor(
  name='MapRequestChunk',
  full_name='proto.MapRequestChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='proto.MapRequestChunk.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=339,
)


_MAPREQUEST = _descriptor.Descriptor(
  name='MapRequest',
  full_name='proto.MapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.MapRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req', full_name='proto.MapRequest.req', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leap_type', full_name='proto.MapRequest.leap_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algo_code', full_name='proto.MapRequest.algo_code', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sites', full_name='proto.MapRequest.sites', index=4,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=467,
)


_MAPRESPONSECHUNK = _descriptor.Descriptor(
  name='MapResponseChunk',
  full_name='proto.MapResponseChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='proto.MapResponseChunk.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=502,
)


_MAPRESPONSE = _descriptor.Descriptor(
  name='MapResponse',
  full_name='proto.MapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='proto.MapResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=535,
)


_MAPRESPONSESCHUNK = _descriptor.Descriptor(
  name='MapResponsesChunk',
  full_name='proto.MapResponsesChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='proto.MapResponsesChunk.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=571,
)


_MAPRESPONSES = _descriptor.Descriptor(
  name='MapResponses',
  full_name='proto.MapResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='proto.MapResponses.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unavailable_sites', full_name='proto.MapResponses.unavailable_sites', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=653,
)

_COMPUTEREQUEST.fields_by_name['leap_type'].enum_type = _LEAPTYPES
_COMPUTEREQUEST.fields_by_name['algo_code'].enum_type = _ALGOCODES
_MAPREQUEST.fields_by_name['leap_type'].enum_type = _LEAPTYPES
_MAPREQUEST.fields_by_name['algo_code'].enum_type = _ALGOCODES
_MAPRESPONSES.fields_by_name['responses'].message_type = _MAPRESPONSE
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeResponse'] = _COMPUTERESPONSE
DESCRIPTOR.message_types_by_name['MapRequestChunk'] = _MAPREQUESTCHUNK
DESCRIPTOR.message_types_by_name['MapRequest'] = _MAPREQUEST
DESCRIPTOR.message_types_by_name['MapResponseChunk'] = _MAPRESPONSECHUNK
DESCRIPTOR.message_types_by_name['MapResponse'] = _MAPRESPONSE
DESCRIPTOR.message_types_by_name['MapResponsesChunk'] = _MAPRESPONSESCHUNK
DESCRIPTOR.message_types_by_name['MapResponses'] = _MAPRESPONSES
DESCRIPTOR.enum_types_by_name['LeapTypes'] = _LEAPTYPES
DESCRIPTOR.enum_types_by_name['AlgoCodes'] = _ALGOCODES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

ComputeResponse = _reflection.GeneratedProtocolMessageType('ComputeResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERESPONSE,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.ComputeResponse)
  })
_sym_db.RegisterMessage(ComputeResponse)

MapRequestChunk = _reflection.GeneratedProtocolMessageType('MapRequestChunk', (_message.Message,), {
  'DESCRIPTOR' : _MAPREQUESTCHUNK,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapRequestChunk)
  })
_sym_db.RegisterMessage(MapRequestChunk)

MapRequest = _reflection.GeneratedProtocolMessageType('MapRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAPREQUEST,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapRequest)
  })
_sym_db.RegisterMessage(MapRequest)

MapResponseChunk = _reflection.GeneratedProtocolMessageType('MapResponseChunk', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSECHUNK,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapResponseChunk)
  })
_sym_db.RegisterMessage(MapResponseChunk)

MapResponse = _reflection.GeneratedProtocolMessageType('MapResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSE,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapResponse)
  })
_sym_db.RegisterMessage(MapResponse)

MapResponsesChunk = _reflection.GeneratedProtocolMessageType('MapResponsesChunk', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSESCHUNK,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapResponsesChunk)
  })
_sym_db.RegisterMessage(MapResponsesChunk)

MapResponses = _reflection.GeneratedProtocolMessageType('MapResponses', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSES,
  '__module__' : 'proto.computation_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.MapResponses)
  })
_sym_db.RegisterMessage(MapResponses)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
