// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/registration-msgs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent by a site connector to a coordinator with the registration request of a site algo.
type SiteRegReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId     int64  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SiteIpPort string `protobuf:"bytes,2,opt,name=site_ip_port,json=siteIpPort,proto3" json:"site_ip_port,omitempty"`
}

func (x *SiteRegReq) Reset() {
	*x = SiteRegReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registration_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteRegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteRegReq) ProtoMessage() {}

func (x *SiteRegReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteRegReq.ProtoReflect.Descriptor instead.
func (*SiteRegReq) Descriptor() ([]byte, []int) {
	return file_proto_registration_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *SiteRegReq) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *SiteRegReq) GetSiteIpPort() string {
	if x != nil {
		return x.SiteIpPort
	}
	return ""
}

// Message sent by a coordinator to a site connector indicating whether the algorithm registration was successful.
type SiteRegRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SiteRegRes) Reset() {
	*x = SiteRegRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registration_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteRegRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteRegRes) ProtoMessage() {}

func (x *SiteRegRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteRegRes.ProtoReflect.Descriptor instead.
func (*SiteRegRes) Descriptor() ([]byte, []int) {
	return file_proto_registration_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *SiteRegRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SiteRegRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_registration_msgs_proto protoreflect.FileDescriptor

var file_proto_registration_msgs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0a, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0c, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69, 0x74, 0x65, 0x49, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x22,
	0x38, 0x0a, 0x0a, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x67, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_registration_msgs_proto_rawDescOnce sync.Once
	file_proto_registration_msgs_proto_rawDescData = file_proto_registration_msgs_proto_rawDesc
)

func file_proto_registration_msgs_proto_rawDescGZIP() []byte {
	file_proto_registration_msgs_proto_rawDescOnce.Do(func() {
		file_proto_registration_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_registration_msgs_proto_rawDescData)
	})
	return file_proto_registration_msgs_proto_rawDescData
}

var file_proto_registration_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_registration_msgs_proto_goTypes = []interface{}{
	(*SiteRegReq)(nil), // 0: proto.SiteRegReq
	(*SiteRegRes)(nil), // 1: proto.SiteRegRes
}
var file_proto_registration_msgs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_registration_msgs_proto_init() }
func file_proto_registration_msgs_proto_init() {
	if File_proto_registration_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_registration_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteRegReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registration_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteRegRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_registration_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_registration_msgs_proto_goTypes,
		DependencyIndexes: file_proto_registration_msgs_proto_depIdxs,
		MessageInfos:      file_proto_registration_msgs_proto_msgTypes,
	}.Build()
	File_proto_registration_msgs_proto = out.File
	file_proto_registration_msgs_proto_rawDesc = nil
	file_proto_registration_msgs_proto_goTypes = nil
	file_proto_registration_msgs_proto_depIdxs = nil
}
