# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/registration-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/registration-msgs.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dproto/registration-msgs.proto\x12\x05proto\"3\n\nSiteRegReq\x12\x0f\n\x07site_id\x18\x01 \x01(\x03\x12\x14\n\x0csite_ip_port\x18\x02 \x01(\t\"*\n\nSiteRegRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\tB\tZ\x07.;protob\x06proto3'
)




_SITEREGREQ = _descriptor.Descriptor(
  name='SiteRegReq',
  full_name='proto.SiteRegReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='proto.SiteRegReq.site_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='site_ip_port', full_name='proto.SiteRegReq.site_ip_port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=91,
)


_SITEREGRES = _descriptor.Descriptor(
  name='SiteRegRes',
  full_name='proto.SiteRegRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.SiteRegRes.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto.SiteRegRes.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['SiteRegReq'] = _SITEREGREQ
DESCRIPTOR.message_types_by_name['SiteRegRes'] = _SITEREGRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SiteRegReq = _reflection.GeneratedProtocolMessageType('SiteRegReq', (_message.Message,), {
  'DESCRIPTOR' : _SITEREGREQ,
  '__module__' : 'proto.registration_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteRegReq)
  })
_sym_db.RegisterMessage(SiteRegReq)

SiteRegRes = _reflection.GeneratedProtocolMessageType('SiteRegRes', (_message.Message,), {
  'DESCRIPTOR' : _SITEREGRES,
  '__module__' : 'proto.registration_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.SiteRegRes)
  })
_sym_db.RegisterMessage(SiteRegRes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
