// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/selector-verification-msgs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent to a site asking it to verify the selector
type SelectorVerificationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId           int64  `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Selector         string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	IsSelectorString bool   `protobuf:"varint,3,opt,name=isSelectorString,proto3" json:"isSelectorString,omitempty"`
}

func (x *SelectorVerificationReq) Reset() {
	*x = SelectorVerificationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_selector_verification_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectorVerificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorVerificationReq) ProtoMessage() {}

func (x *SelectorVerificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_selector_verification_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorVerificationReq.ProtoReflect.Descriptor instead.
func (*SelectorVerificationReq) Descriptor() ([]byte, []int) {
	return file_proto_selector_verification_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *SelectorVerificationReq) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *SelectorVerificationReq) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SelectorVerificationReq) GetIsSelectorString() bool {
	if x != nil {
		return x.IsSelectorString
	}
	return false
}

// Message returned from a site indicating whether verification was successful
type SelectorVerificationRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteId  int64  `protobuf:"varint,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SelectorVerificationRes) Reset() {
	*x = SelectorVerificationRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_selector_verification_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectorVerificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorVerificationRes) ProtoMessage() {}

func (x *SelectorVerificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_selector_verification_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorVerificationRes.ProtoReflect.Descriptor instead.
func (*SelectorVerificationRes) Descriptor() ([]byte, []int) {
	return file_proto_selector_verification_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *SelectorVerificationRes) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *SelectorVerificationRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SelectorVerificationRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Message sent to verify the selector across all the sites
type SelectorVerificationsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector         string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	IsSelectorString bool   `protobuf:"varint,2,opt,name=isSelectorString,proto3" json:"isSelectorString,omitempty"`
}

func (x *SelectorVerificationsReq) Reset() {
	*x = SelectorVerificationsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_selector_verification_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectorVerificationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorVerificationsReq) ProtoMessage() {}

func (x *SelectorVerificationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_selector_verification_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorVerificationsReq.ProtoReflect.Descriptor instead.
func (*SelectorVerificationsReq) Descriptor() ([]byte, []int) {
	return file_proto_selector_verification_msgs_proto_rawDescGZIP(), []int{2}
}

func (x *SelectorVerificationsReq) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SelectorVerificationsReq) GetIsSelectorString() bool {
	if x != nil {
		return x.IsSelectorString
	}
	return false
}

// Message returned with a list of verification results
type SelectorVerificationsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*SelectorVerificationRes `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *SelectorVerificationsRes) Reset() {
	*x = SelectorVerificationsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_selector_verification_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectorVerificationsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorVerificationsRes) ProtoMessage() {}

func (x *SelectorVerificationsRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_selector_verification_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorVerificationsRes.ProtoReflect.Descriptor instead.
func (*SelectorVerificationsRes) Descriptor() ([]byte, []int) {
	return file_proto_selector_verification_msgs_proto_rawDescGZIP(), []int{3}
}

func (x *SelectorVerificationsRes) GetResponses() []*SelectorVerificationRes {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_proto_selector_verification_msgs_proto protoreflect.FileDescriptor

var file_proto_selector_verification_msgs_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2d, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x79, 0x0a, 0x17, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2a,
	0x0a, 0x10, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x61, 0x0a, 0x17, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x62, 0x0a,
	0x18, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x22, 0x58, 0x0a, 0x18, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_selector_verification_msgs_proto_rawDescOnce sync.Once
	file_proto_selector_verification_msgs_proto_rawDescData = file_proto_selector_verification_msgs_proto_rawDesc
)

func file_proto_selector_verification_msgs_proto_rawDescGZIP() []byte {
	file_proto_selector_verification_msgs_proto_rawDescOnce.Do(func() {
		file_proto_selector_verification_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_selector_verification_msgs_proto_rawDescData)
	})
	return file_proto_selector_verification_msgs_proto_rawDescData
}

var file_proto_selector_verification_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_selector_verification_msgs_proto_goTypes = []interface{}{
	(*SelectorVerificationReq)(nil),  // 0: proto.SelectorVerificationReq
	(*SelectorVerificationRes)(nil),  // 1: proto.SelectorVerificationRes
	(*SelectorVerificationsReq)(nil), // 2: proto.SelectorVerificationsReq
	(*SelectorVerificationsRes)(nil), // 3: proto.SelectorVerificationsRes
}
var file_proto_selector_verification_msgs_proto_depIdxs = []int32{
	1, // 0: proto.SelectorVerificationsRes.responses:type_name -> proto.SelectorVerificationRes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_selector_verification_msgs_proto_init() }
func file_proto_selector_verification_msgs_proto_init() {
	if File_proto_selector_verification_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_selector_verification_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectorVerificationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_selector_verification_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectorVerificationRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_selector_verification_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectorVerificationsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_selector_verification_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectorVerificationsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_selector_verification_msgs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_selector_verification_msgs_proto_goTypes,
		DependencyIndexes: file_proto_selector_verification_msgs_proto_depIdxs,
		MessageInfos:      file_proto_selector_verification_msgs_proto_msgTypes,
	}.Build()
	File_proto_selector_verification_msgs_proto = out.File
	file_proto_selector_verification_msgs_proto_rawDesc = nil
	file_proto_selector_verification_msgs_proto_goTypes = nil
	file_proto_selector_verification_msgs_proto_depIdxs = nil
}
