# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user-msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/user-msgs.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/user-msgs.proto\x12\x05proto\"*\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\nUserRegReq\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.proto.User\"\x1d\n\nUserRegRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x0bUserAuthReq\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.proto.User\"-\n\x0bUserAuthRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\tB\tZ\x07.;protob\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='proto.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='proto.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='proto.User.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=74,
)


_USERREGREQ = _descriptor.Descriptor(
  name='UserRegReq',
  full_name='proto.UserRegReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='proto.UserRegReq.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=115,
)


_USERREGRES = _descriptor.Descriptor(
  name='UserRegRes',
  full_name='proto.UserRegRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.UserRegRes.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=146,
)


_USERAUTHREQ = _descriptor.Descriptor(
  name='UserAuthReq',
  full_name='proto.UserAuthReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='proto.UserAuthReq.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=188,
)


_USERAUTHRES = _descriptor.Descriptor(
  name='UserAuthRes',
  full_name='proto.UserAuthRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.UserAuthRes.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='proto.UserAuthRes.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=235,
)

_USERREGREQ.fields_by_name['user'].message_type = _USER
_USERAUTHREQ.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserRegReq'] = _USERREGREQ
DESCRIPTOR.message_types_by_name['UserRegRes'] = _USERREGRES
DESCRIPTOR.message_types_by_name['UserAuthReq'] = _USERAUTHREQ
DESCRIPTOR.message_types_by_name['UserAuthRes'] = _USERAUTHRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'proto.user_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.User)
  })
_sym_db.RegisterMessage(User)

UserRegReq = _reflection.GeneratedProtocolMessageType('UserRegReq', (_message.Message,), {
  'DESCRIPTOR' : _USERREGREQ,
  '__module__' : 'proto.user_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserRegReq)
  })
_sym_db.RegisterMessage(UserRegReq)

UserRegRes = _reflection.GeneratedProtocolMessageType('UserRegRes', (_message.Message,), {
  'DESCRIPTOR' : _USERREGRES,
  '__module__' : 'proto.user_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserRegRes)
  })
_sym_db.RegisterMessage(UserRegRes)

UserAuthReq = _reflection.GeneratedProtocolMessageType('UserAuthReq', (_message.Message,), {
  'DESCRIPTOR' : _USERAUTHREQ,
  '__module__' : 'proto.user_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserAuthReq)
  })
_sym_db.RegisterMessage(UserAuthReq)

UserAuthRes = _reflection.GeneratedProtocolMessageType('UserAuthRes', (_message.Message,), {
  'DESCRIPTOR' : _USERAUTHRES,
  '__module__' : 'proto.user_msgs_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserAuthRes)
  })
_sym_db.RegisterMessage(UserAuthRes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
